server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy /api requests to Spring Boot backend
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
    }

    # Proxy WebSocket to Spring Boot backend
    location /ws/ {
        proxy_pass http://backend:8080/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # Thêm cấu hình cache dài hạn cho file static (js, css, img) vì Angular đã tự sinh Hash code
    location ~* \.(?:css|js|woff2?|eot|ttf|svg|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    # SPA fallback — serve index.html for all Angular routes, đồng thời TẮT CACHE hoàn toàn
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }
}
